working on versioning tests

diff --git a/tests b/tests
--- a/tests
+++ b/tests
@@ -15,21 +15,21 @@ case $OSTYPE in
 (darwin*)
   platform=darwin
   declare -a versions=(
-    #"0.7.3"
     #"0.8.3"
     #"0.9.6"
     #"0.10.4"
-    "0.11.4"
+    #"0.11.6"
+    "1.0.1"
   )
   ;;
 (linux*)
   platform=linux
   declare -a versions=(
-    "0.7.3"
-    "0.8.3"
-    "0.9.6"
-    "0.10.4"
-    "0.11.4"
+    #"0.8.3"
+    #"0.9.6"
+    #"0.10.4"
+    #"0.11.6"
+    "1.0.1"
   )
   ;;
 (*)
@@ -315,7 +315,9 @@ for version in "${versions[@]}"; do
   killall vault-${platform}-${version} >/dev/null 2>&1 || true
 done
 for version in "${versions[@]}"; do
-for kvversion in 1 2; do
+# TODO: Put this back
+#for kvversion in 1 2; do
+for kvversion in 2; do
   # KV v2 was introduced in 0.10
   if [[ kvversion -eq 2 && $version =~ ^0\.[6-9].* ]]; then
     continue
@@ -356,6 +358,7 @@ for kvversion in 1 2; do
   restart_vault_server
   clearvault
 
+: <<'BLOCK_COMMENT'
 
   ########    ###    ########   ######   ######## ########
      ##      ## ##   ##     ## ##    ##  ##          ##
@@ -1747,7 +1750,7 @@ EOF
 
   #######
   clearvault
-  testing ${version} tree --keys
+  testing tree --keys
   generate secret/tree/a/b/c   subkey=foo
   generate secret/tree/a/b/c/d subsubkey=bar
   generate secret/tree/robot   mark=val password=sekrit username=robo
@@ -1796,7 +1799,7 @@ EOF
 
   #######
   clearvault
-  testing ${version} paths --keys
+  testing paths --keys
   no_key secret/{a/b/c,robot}
   generate secret/a/b/c   subkey=value
   generate secret/a/b/c/d subsubkey=value
@@ -1833,7 +1836,7 @@ EOF
 
   #######
   clearvault
-  testing ${version} tree export
+  testing tree export
   no_key secret/export{,/admin,/robot,/a/b/c}
   generate secret/export/admin username=admin password=sekrit
   generate secret/export/robot username=bot password=beep-boop mark=2
@@ -1896,7 +1899,7 @@ EOF
 
   #######
   clearvault
-  testing ${version} tree import
+  testing tree import
   cat <<EOF >t/home/want
 [
   {
@@ -1965,7 +1968,7 @@ EOF
   ##    ##  ##       ##   ##  ##          ##
   ##     ## ######## ##    ## ########    ##
 
-  testing ${version} safe rekey
+  testing safe rekey
   now trying to rekey to require 5/3 keys should error
   (run; ./safe rekey --keys 3 --threshold 5 >t/home/got 2>&1); exitok $? 1
   cat <<'EOF' > t/home/want ; diffok
@@ -2014,7 +2017,7 @@ EOF
   rm t/home/original
 
   if [[ -z "${SAFE_DISABLE_GPG_TESTS:-}" ]]; then
-    testing ${version} safe rekey --gpg
+    testing safe rekey --gpg
     now trying to rekey with the threshold other than the number of gpg keys should error
     gpg --import assets/gpg.pubkey
     (run; ./safe rekey --keys 3 --gpg safe-testing@safe.com >t/home/got 2>&1); exitok $? 1
@@ -2055,6 +2058,252 @@ knock: knock
 
 EOF
   fi
+
+BLOCK_COMMENT
+
+  if [[ $kvversion -ne 2 ]]; then continue; fi
+
+
+  # KV Version 2 specific tests
+  testing setting multiple versions
+  clearvault
+  # the default version limit in vault is 10. If we write eleven, we can
+  # test that the count not starting at version 1 works - we would expect 
+  # the first remaining version to be version 2
+  now setting eleven versions of the same key
+  values=(eins zwei drei vier fuenf sechs sieben acht neun zehn elf)
+  for val in "${values[@]}"; do
+    (./safe set secret/versioned key=${val} 2>/dev/null); exitok $? 0
+  done
+
+  now checking that not specifying a version gets the latest version
+  (./safe get secret/versioned >t/home/got); exitok $? 0
+  cat <<'EOF' >t/home/want; diffok
+--- # secret/versioned
+key: elf
+
+EOF
+
+  for vnum in $(seq 2 11); do
+    now checking that version ${vnum} can be retrieved
+    (./safe get secret/versioned^${vnum} >t/home/got); exitok $? 0
+    cat <<EOF >t/home/want; diffok
+--- # secret/versioned^${vnum}
+key: ${values[${vnum}-1]}
+
+EOF
+  done
+
+  # If the default number of versions stops being 10, this would fail
+  now checking that retrieving a missing version returns an error
+  (./safe get secret/versioned^1 2>t/home/got); exitok $? 1
+  cat <<'EOF' >t/home/want; diffok
+!! no secret exists at path `secret/versioned`
+EOF
+
+  testing versions 
+  now testing the output of versions
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  # The whitespace below between version num and status is a tab
+  cat <<'EOF' >t/home/want; diffok
+2	alive
+3	alive
+4	alive
+5	alive
+6	alive
+7	alive
+8	alive
+9	alive
+10	alive
+11	alive
+EOF
+
+  testing deleting specific versions
+  clearvault
+  now putting secret versions into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now deleting version two
+  (./safe delete secret/versioned^2 >/dev/null); exitok $? 0
+  now checking the version list
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  cat << 'EOF' >t/home/want; diffok
+1	alive
+2	deleted
+3	alive
+EOF
+    
+  testing deleting the latest version
+  clearvault
+  now putting secret versions into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now deleting the latest version
+  (./safe delete secret/versioned >/dev/null); exitok $? 0
+  now checking the version list
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  cat << 'EOF' >t/home/want; diffok
+1	alive
+2	alive
+3	deleted
+EOF
+    
+  
+  testing destroying specific versions
+  clearvault
+  now putting secret versions into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now destroying version two
+  (./safe delete -D secret/versioned^2 >/dev/null); exitok $? 0
+  now checking the version list
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  cat << 'EOF' >t/home/want; diffok
+1	alive
+2	destroyed
+3	alive
+EOF
+
+  testing destroying the latest version
+  clearvault
+  now putting secret versions into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now destroying the latest version
+  (./safe delete -D secret/versioned >/dev/null); exitok $? 0
+  now checking the version list
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  cat << 'EOF' >t/home/want; diffok
+1	alive
+2	alive
+3	destroyed
+EOF
+
+  testing deleting already deleted versions
+  clearvault
+  now putting a secret into the vault
+  (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  now deleting the secret
+  (./safe delete secret/versioned >/dev/null); exitok $? 0
+  now deleting the same secret again
+  (./safe delete secret/versioned >/dev/null 2>t/home/got); exitok $? 1
+  now checking that the error message conveys that the secret is already deleted
+  cat << 'EOF' >t/home/want; diffok
+!! `secret/versioned' is deleted
+EOF
+
+  testing deleting already deleted versions with force
+  clearvault
+  now putting a secret into the vault
+  (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  now deleting the secret
+  (./safe delete -f secret/versioned >/dev/null); exitok $? 0
+  now deleting the same secret again
+  (./safe delete -f secret/versioned >/dev/null 2>t/home/got); exitok $? 0
+    
+  testing destroying specific versions that are already marked as deleted
+  clearvault
+  now putting secret versions into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now deleting version two
+  (./safe delete secret/versioned^2 >/dev/null); exitok $? 0
+  now destroying version two
+  (./safe delete -D secret/versioned^2 >/dev/null); exitok $? 0
+  now checking the version list
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  cat << 'EOF' >t/home/want; diffok
+1	alive
+2	destroyed
+3	alive
+EOF
+
+  testing destroying already destroyed versions
+  clearvault
+  now putting a secret into the vault
+  (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  now destroying the secret
+  (./safe delete secret/versioned -D >/dev/null); exitok $? 0
+  now destroying the same secret again
+  (./safe delete secret/versioned -D 2>t/home/got); exitok $? 1
+  now checking that the error message conveys that the secret is already destroyed
+  cat << 'EOF' >t/home/want; diffok
+!! `secret/versioned' is destroyed
+EOF
+
+  testing destroying already destroyed versions with force
+  clearvault
+  now putting a secret into the vault
+  (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  now destroying the secret
+  (./safe delete secret/versioned -Df); exitok $? 0
+  now destroying the same secret again
+  (./safe delete secret/versioned -Df); exitok $? 0
+
+  testing deleting all versions
+  clearvault
+  now putting three versions of a secret into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now deleting all versions
+  (./safe delete secret/versioned -a); exitok $? 0
+  now getting versions metadata
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  now checking that all versions are deleted
+  cat << 'EOF' >t/home/want; diffok
+1	deleted
+2	deleted
+3	deleted
+EOF
+
+  testing deleting all versions with the latest version deleted already
+  clearvault
+  now putting three versions of a secret into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now deleting the latest version
+  (./safe delete secret/versioned); exitok $? 0
+  now deleting all versions
+  (./safe delete secret/versioned -a); exitok $? 0
+  now getting versions metadata
+  (./safe versions secret/versioned >t/home/got); exitok $? 0
+  now checking that all versions are deleted
+  cat << 'EOF' >t/home/want; diffok
+1	deleted
+2	deleted
+3	deleted
+EOF
+
+  testing destroying all versions
+  clearvault
+  now putting three versions of a secret into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now destroying all versions
+  (./safe delete secret/versioned -Da 2>/dev/null); exitok $? 0
+  now checking that versions metadata is gone
+  (./safe versions secret/versioned >t/home/got 2>/dev/null); exitok $? 1
+
+  testing destroying all versions when the latest version is already destroyed
+  clearvault
+  now putting three versions of a secret into the vault
+  for vnum in $(seq 1 3); do
+    (./safe set secret/versioned key=val 2>/dev/null); exitok $? 0
+  done
+  now destroying the latest version
+  (./safe delete secret/versioned -D 2>/dev/null); exitok $? 0
+  now destroying all versions
+  (./safe delete secret/versioned -Da 2>/dev/null); exitok $? 0
+  now checking that versions metadata is gone
+  (./safe versions secret/versioned >t/home/got 2>/dev/null); exitok $? 1
 
   dump_log
 done
@@ -2253,7 +2502,7 @@ EOF
 
   #######
   clearvault
-  testing ${version} x509 commands
+  testing x509 commands
 
   now running safe x509 issue without a path
   (run; ./safe x509 issue)                                                ; exitok $? 1
