Overhaul Command-line Handling
Drop getopt in favor of a more flexible underlying library that natively
supports chained command execution with sub-flags and all the niceties
operators expect.

Every care has been taken to maintain existing calling conventions and
preserve established semantics.  The following changes go against that:

  - `gen` regained it's `--policy` argument; this was the change (#44)
    that brought #70 to our attention in the first place.
  - Commands that failed their recursive force check (copy, move,
    delete) would cause an entire chain of sub-commands to fail.  Now,
    only the affected sub-command is affected, and subsequent
    sub-commands will be executed.

This new CLI library is much more foregiving about sub-command flags.
It also allows global options to appear anywhere inside the command
line, allowing operators to tack a `-k` onto the end of a failing login
command, without too much fuss.

Primarily, this change fixes #70.

diff --git a/tests b/tests
--- a/tests
+++ b/tests
@@ -153,22 +153,35 @@ EOF
 		echo "ok"
 	fi
 
-#	testing $version custom password runes randomization
-#
-#	./safe gen --policy "1-9" 64 secret/random one #    >/dev/null
-#	./safe get secret/random | spruce json >t/home/runed # 2>t/home/errors
-#
-#	one=$(jq -r .one < t/home/runed)
-#	if [[ "$one" =~ ^[1-9]+$ ]]; then
-#		echo "ok"
-#	else
-#		echo "FAILED"
-#		rc=1
-#		echo "	expected generated password:"
-#		echo "		|"$one"|"
-#		echo "	to only contain:"
-#		echo "	1-9"
-#	fi
+	testing $version command chaining
+	./safe gen secret/chained a -- gen secret/chained b -- gen secret/chained c >/dev/null
+	./safe get secret/chained | spruce json > t/home/got 2>t/home/errors
+	for k in a b c; do
+		v=$(jq -r .$k < t/home/got)
+		if [[ -z "$v" ]]; then
+			echo "FAILED"
+			rc=1
+			echo "  ... expected secret/chained/$k to exist"
+		else
+			echo "ok"
+		fi
+	done
+
+
+	testing $version custom password runes randomization
+
+	./safe gen --policy "1-9" 64 secret/random one #    >/dev/null
+	./safe get secret/random | spruce json >t/home/runed # 2>t/home/errors
+
+	one=$(jq -r .one < t/home/runed)
+	if [[ "$one" =~ ^[1-9]+$ ]]; then
+		echo "ok"
+	else
+		echo "FAILED"
+		rc=1
+		echo "  expected generated password: '$one'"
+		echo "              to only contain: [1-9]"
+	fi
 
 	testing $version single-value retrieval
 	./safe set secret/single/value foo=bar baz=quux >/dev/null
@@ -265,6 +278,10 @@ EOF
 	kill $vault_pid
 	echo
 	echo
+
+	if grep -q 'goroutine' t/home/log; then
+		exit 77 # ./try will pick up on this error code
+	fi
 done
 
 if [[ ${rc} -eq 0 ]]; then
